cmake_minimum_required(VERSION 3.28)
include("${VALIDATION_MODULE}")
set(publisher ON)
set(config fixture.json)
set(client_id fixture-id)
set(client_secret fixture-value)
set(hooks OFF)
if(CASE STREQUAL "empty")
  set(config "")
elseif(CASE STREQUAL "missing_id")
  set(client_id "")
elseif(CASE STREQUAL "missing_secret")
  set(client_secret "")
elseif(CASE STREQUAL "whitespace")
  set(client_secret "  ")
elseif(CASE STREQUAL "hooks")
  set(hooks ON)
elseif(CASE STREQUAL "oss")
  set(publisher OFF)
  set(config "")
  set(client_id "")
  set(client_secret "")
  set(hooks ON)
elseif(NOT CASE STREQUAL "complete")
  message(FATAL_ERROR "Unknown test case")
endif()
dsk_validate_release_configuration("${publisher}" "${config}" "${client_id}" "${client_secret}" "${hooks}")
