foreach(required_file IN ITEMS CMAKE_LIST CONFIGURE_SCRIPT BUILD_SCRIPT EXTERNAL_SIGNING_SCRIPT)
  if(NOT DEFINED ${required_file} OR NOT EXISTS "${${required_file}}")
    message(FATAL_ERROR "${required_file} must point to an existing file")
  endif()
endforeach()

file(READ "${CMAKE_LIST}" cmake_source)
if(NOT cmake_source MATCHES "option\\(DSK_PUBLISHER_RELEASE \"Require publisher OAuth credentials for release builds\" OFF\\)")
  message(FATAL_ERROR "CMake must expose the opt-in publisher release gate")
endif()
if(NOT cmake_source MATCHES "DSK_PUBLISHER_RELEASE")
  message(FATAL_ERROR "CMake must enforce publisher release requirements")
endif()

file(READ "${CONFIGURE_SCRIPT}" configure_source)
if(NOT configure_source MATCHES "\\[switch\\]\\$PublisherRelease")
  message(FATAL_ERROR "Windows configure script must expose PublisherRelease")
endif()
if(NOT configure_source MATCHES "DDSK_PUBLISHER_RELEASE")
  message(FATAL_ERROR "Windows configure script must pass DSK_PUBLISHER_RELEASE")
endif()

file(READ "${BUILD_SCRIPT}" build_source)
if(NOT build_source MATCHES "\\[switch\\]\\$RequirePublisherRelease")
  message(FATAL_ERROR "Installer script must expose RequirePublisherRelease")
endif()
if(NOT build_source MATCHES "oauth-publisher-config")
  message(FATAL_ERROR "Installer script must validate generated publisher OAuth config")
endif()

file(READ "${EXTERNAL_SIGNING_SCRIPT}" signing_source)
if(NOT signing_source MATCHES "ExpectedSignerThumbprint")
  message(FATAL_ERROR "External signing requires an expected signer thumbprint")
endif()
if(signing_source MATCHES "\\$expectedSigner = \\$pluginSignature")
  message(FATAL_ERROR "External signing must not derive the expected signer from the plugin")
endif()
if(NOT signing_source MATCHES "same signer")
  message(FATAL_ERROR "External signing must retain same-signer validation")
endif()

message(STATUS "Publisher OAuth and pinned signer release gates are present")
