if(NOT DEFINED CMAKE_LIST OR NOT EXISTS "${CMAKE_LIST}")
  message(FATAL_ERROR "CMAKE_LIST must point to the project CMakeLists.txt")
endif()
if(NOT DEFINED PLUGIN_MAIN OR NOT EXISTS "${PLUGIN_MAIN}")
  message(FATAL_ERROR "PLUGIN_MAIN must point to plugin-main.cpp")
endif()
foreach(required_file IN ITEMS VERTICAL_EDITOR_HPP VERTICAL_EDITOR_CPP INSTALLER_SCRIPT PLUGIN_DLL)
  if(NOT DEFINED ${required_file} OR NOT EXISTS "${${required_file}}")
    message(FATAL_ERROR "${required_file} must point to an existing file")
  endif()
endforeach()

file(READ "${CMAKE_LIST}" cmake_source)
string(FIND "${cmake_source}" "option(DSK_INCLUDE_E2E_HOOKS \"Compile OBS E2E automation hooks into the plugin\" OFF)" option_position)
if(option_position LESS 0)
  message(FATAL_ERROR "Release builds must disable DSK E2E hooks by default")
endif()
if(NOT cmake_source MATCHES "if\\(DSK_INCLUDE_E2E_HOOKS\\)")
  message(FATAL_ERROR "E2E sources must be added only when DSK_INCLUDE_E2E_HOOKS is enabled")
endif()

file(READ "${PLUGIN_MAIN}" plugin_source)
file(READ "${VERTICAL_EDITOR_HPP}" vertical_header)
file(READ "${VERTICAL_EDITOR_CPP}" vertical_source)
foreach(source_text IN ITEMS plugin_source vertical_header vertical_source)
  if(NOT "${${source_text}}" MATCHES "#ifdef DSK_INCLUDE_E2E_HOOKS")
    message(FATAL_ERROR "${source_text} must guard E2E-only declarations and definitions")
  endif()
endforeach()

file(READ "${INSTALLER_SCRIPT}" installer_source)
if(NOT installer_source MATCHES "DSK_INCLUDE_E2E_HOOKS:BOOL=OFF")
  message(FATAL_ERROR "The distribution installer must reject a hook-enabled build tree")
endif()
if(NOT installer_source MATCHES "DSK_E2E_VERTICAL_UI_STRESS")
  message(FATAL_ERROR "The distribution installer must inspect the DLL for E2E markers")
endif()

file(STRINGS "${PLUGIN_DLL}" binary_e2e_markers REGEX "DSK_E2E_(AUTORUN|VERTICAL_UI_STRESS)")
if(HOOKS_ENABLED)
  if(NOT binary_e2e_markers)
    message(FATAL_ERROR "The E2E build does not contain its required automation markers")
  endif()
else()
  if(binary_e2e_markers)
    message(FATAL_ERROR "The release plugin binary contains E2E automation markers")
  endif()
endif()

message(STATUS "E2E hook source, binary, and installer boundaries are valid")
