if(NOT DEFINED STREAM_CONTROLS_CPP OR NOT EXISTS "${STREAM_CONTROLS_CPP}")
  message(FATAL_ERROR "STREAM_CONTROLS_CPP must point to stream-controls-dock.cpp")
endif()

file(READ "${STREAM_CONTROLS_CPP}" stream_controls_source)
string(FIND "${stream_controls_source}" "void StreamControlsDock::refresh()" refresh_start)
string(FIND "${stream_controls_source}" "void StreamControlsDock::handleObsNativeStreamingStateChanged" refresh_end)
if(refresh_start LESS 0 OR refresh_end LESS 0 OR refresh_end LESS_EQUAL refresh_start)
  message(FATAL_ERROR "Unable to locate the Stream Controls refresh implementation")
endif()

math(EXPR refresh_length "${refresh_end} - ${refresh_start}")
string(SUBSTRING "${stream_controls_source}" ${refresh_start} ${refresh_length} refresh_body)
if(refresh_body MATCHES "clearButtons\\(\\)")
  message(FATAL_ERROR "Stream Controls refresh must reuse rows instead of deleting every QWidget")
endif()
if(NOT stream_controls_source MATCHES "updateTargetRow")
  message(FATAL_ERROR "Stream Controls must update retained target rows in place")
endif()
if(NOT stream_controls_source MATCHES "removeStaleTargetRows")
  message(FATAL_ERROR "Stream Controls must explicitly remove only rows for deleted targets")
endif()

message(STATUS "Stream Controls refresh reuses retained rows")
