foreach(required MAIN_DOCK_CPP MAIN_DOCK_HPP STREAM_CONTROLS_CPP STREAM_CONTROLS_HPP)
  if(NOT DEFINED ${required} OR NOT EXISTS "${${required}}")
    message(FATAL_ERROR "${required} must point to an existing source file")
  endif()
endforeach()

file(READ "${MAIN_DOCK_CPP}" main_dock_cpp)
file(READ "${MAIN_DOCK_HPP}" main_dock_hpp)
file(READ "${STREAM_CONTROLS_CPP}" controls_cpp)
file(READ "${STREAM_CONTROLS_HPP}" controls_hpp)

if(main_dock_cpp MATCHES "dskStreamingPageTitle" OR main_dock_hpp MATCHES "pageTitle_")
  message(FATAL_ERROR "The selected page must be expressed by the OBS dock title, not a second in-dock heading")
endif()
if(NOT main_dock_cpp MATCHES "navigationBar->addWidget\\(menuButton_\\)")
  message(FATAL_ERROR "The page/settings menu must live in the lower-left navigation bar")
endif()
if(NOT main_dock_cpp MATCHES "QStringLiteral\\(\"DSK Streaming\"\\)" OR
   NOT main_dock_cpp MATCHES "dock->setWindowTitle\\(dockTitle\\)")
  message(FATAL_ERROR "The actual OBS dock title must remain DSK Streaming on every page")
endif()
if(controls_cpp MATCHES "stopAll_" OR controls_hpp MATCHES "stopAll_")
  message(FATAL_ERROR "Start All and Stop All must be one state-dependent control")
endif()
if(NOT controls_cpp MATCHES "allToggle_->setText" OR NOT controls_hpp MATCHES "allToggle_")
  message(FATAL_ERROR "The all-stream control must update its label from current state")
endif()
if(NOT controls_cpp MATCHES "setFixedWidth\\(64\\)")
  message(FATAL_ERROR "Per-stream Start/Stop controls must keep the compact 64px width")
endif()

message(STATUS "Streaming dock uses the compact, state-dependent control surface")
