function(dsk_validate_release_configuration publisher config client_id client_secret hooks)
  if(publisher)
    foreach(field IN ITEMS config client_id client_secret)
      string(STRIP "${${field}}" value)
      if(value STREQUAL "")
        message(FATAL_ERROR "Publisher release requires complete OAuth configuration")
      endif()
    endforeach()
    if(hooks)
      message(FATAL_ERROR "Publisher release requires E2E hooks disabled")
    endif()
  endif()
endfunction()
